In [24]:
import numpy as np
from scipy.stats import skew, kurtosis
from joblib import Parallel, delayed
from scipy import stats

In [19]:
# Creating a matrix
matrix_A = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", matrix_A)

# Reshaping a matrix
reshaped_matrix = np.reshape(matrix_A, (4, 1))
print("Reshaped Matrix:\n", reshaped_matrix)

# Changing values in a matrix
matrix_A[0, 0] = 5
print("Updated Matrix A:\n", matrix_A)

Matrix A:
 [[1 2]
 [3 4]]
Reshaped Matrix:
 [[1]
 [2]
 [3]
 [4]]
Updated Matrix A:
 [[5 2]
 [3 4]]


In [20]:
# Example survey data matrix (5 respondents, 4 questions)
survey_data = np.array([[5, 1, 4, 4],
                        [4, 2, 4, 3],
                        [5, 1, 1, 5],
                        [3, 2, 1, 2],
                        [2, 1, 2, 5]])

# Calculating various statistics
average_responses = np.mean(survey_data, axis=0)
total_responses = np.sum(survey_data, axis=0)
max_responses = np.max(survey_data, axis=0)
min_responses = np.min(survey_data, axis=0)

print("Average Responses:", average_responses)
print("Total Responses:", total_responses)
print("Maximum Responses:", max_responses)
print("Minimum Responses:", min_responses)

Average Responses: [3.8 1.4 2.4 3.8]
Total Responses: [19  7 12 19]
Maximum Responses: [5 2 4 5]
Minimum Responses: [2 1 1 2]


In [2]:
# Annual returns of the investment
returns = np.array([0.08, 0.12, -0.05, 0.10, 0.07])

# Calculating mean return
mean_return = np.mean(returns)
print("Mean return of the investment:", mean_return)
# Calculating variance
variance = np.var(returns)
print("Variance of the investment returns:", variance)

Mean return of the investment: 0.064
Variance of the investment returns: 0.003544


In [3]:
# Example dataset (heights in cm)
heights = np.array([170, 165, 180, 175, 160, 155, 185, 190, 165, 175])  # Example data

mean_height = np.mean(heights)
variance_height = np.var(heights)
print("\nMean height:", mean_height)
print("Variance of heights:", variance_height)
# Calculating skewness and kurtosis
skewness = skew(heights)
kurtosis_value = kurtosis(heights)

print("Skewness:", skewness)
print("Kurtosis:", kurtosis_value)


Mean height: 172.0
Variance of heights: 111.0
Skewness: 0.10774225897731068
Kurtosis: -0.9963476990504017


In [4]:
# Create a large array
large_array = np.arange(1000000)

# Inspect memory layout
print("Array size:", large_array.size)
print("Item size:", large_array.itemsize)
print("Memory usage (bytes):", large_array.size * large_array.itemsize)

Array size: 1000000
Item size: 8
Memory usage (bytes): 8000000


In [5]:
# Check memory contiguity
print("C-contiguous:", large_array.flags['C_CONTIGUOUS'])
print("F-contiguous:", large_array.flags['F_CONTIGUOUS'])

C-contiguous: True
F-contiguous: True


In [11]:
# Vectorized addition
result = large_array + large_array
print("First 5 results of vectorized addition:", result[:5])

First 5 results of vectorized addition: [0 2 4 6 8]


In [12]:
# Broadcasting a smaller array
small_array = np.array([1, 2, 3])
broadcasted_result = large_array[:3] + small_array
print("Broadcasted Result:", broadcasted_result)

Broadcasted Result: [1 3 5]


In [17]:
# Parallel computation using Joblib
def compute(x):
    return x * x

result = Parallel(n_jobs=4)(delayed(compute)(i) for i in large_array)

In [18]:
print("First 5 results of parallel computation:", result[:5])

First 5 results of parallel computation: [np.int64(0), np.int64(1), np.int64(4), np.int64(9), np.int64(16)]


In [34]:
# Sample data (engagement time in minutes)
sample_data = np.arange(15,20)  # Example data
print("Sample data:", sample_data)

# Performing a one-sample t-test
t_statistic, p_value = stats.ttest_1samp(sample_data, 15)

# Interpreting the result
alpha = 0.05  # Significance level
if p_value < alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")


Sample data: [15 16 17 18 19]
Reject the null hypothesis
