In [3]:
import numpy as np

In [5]:
# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

1D Array: [1 2 3 4]


In [6]:
# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3]
#  [4 5 6]]

2D Array:
 [[1 2 3]
 [4 5 6]]


In [7]:
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

Shape: (2, 3)
Size: 6
Data Type: int64


In [12]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Output:
# 3D Array: 
# [[[1 2]
#   [3 4]]
#
#  [[5 6]
#   [7 8]]]
# Shape: (2, 2, 2), Size: 8
print("3D Array:\n", array_3d)
print("Shape:", array_3d.shape)  # Expected Output: Shape: (2, 2, 2)
print("Size:", array_3d.size)    # Expected Output: Size: 8
print("Data Type:", array_3d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Size: 8
Data Type: int64


In [13]:
array_2d_large = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# Output:
# Larger 2D Array: 
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
# Shape: (3, 4), Size: 12

In [14]:
print("Larger 2D Array:\n", array_2d_large)
print("Shape:", array_2d_large.shape)  # Expected Output: Shape: (3, 4)
print("Size:", array_2d_large.size)    # Expected Output: Size: 12
print("Data Type:", array_2d_large.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

Larger 2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Size: 12
Data Type: int64


In [15]:
array_1D = np.array([1, 2, 3, 4])
print("1D Array:\n", array_1D)
print("Shape:", array_1D.shape)  # Expected Output: Shape: (4,)
print("Size:", array_1D.size)    # Expected Output: Size: 4
print("Data Type:", array_1D.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)


1D Array:
 [1 2 3 4]
Shape: (4,)
Size: 4
Data Type: int64


In [ ]:
array_1D.reshape(2, 2)


array([[1, 2],
       [3, 4]])

In [19]:
arr = np.array([1, 2, 3, 4])
print("Original Array:", arr)  # Expected Output: Original Array: [1 2 3 4]

arr_1 = arr.astype(float)
print("Array with float data type:", arr_1)  # Expected Output: Array with float data type: [1. 2. 3. 4.]
print("Data Type:", arr_1.dtype)  # Expected Output: Data Type: float64 (or similar, depending on system)


Original Array: [1 2 3 4]
Array with float data type: [1. 2. 3. 4.]
Data Type: float64


In [20]:
# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("2D Array:\n", array_2d)


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

Element at row 1, column 2: 6


In [22]:
# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

Second row: [4 5 6]


In [23]:
# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Third column: [3 6 9]


In [4]:
# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

Slice of the array: [[2 3]
 [5 6]]


In [6]:
# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]
