# 🌟 Exercise 1 : Array Creation and Manipulation
## Instructions
## Create a 1D NumPy array containing numbers from 0 to 9.




# 🌟 Exercise 2 : Type Conversion and Array Operations
## Instructions
## Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.




# 🌟 Exercise 3 : Working with Multi-Dimensional Arrays
## Instructions
## Create a 3x3 NumPy array with values ranging from 1 to 9.




# 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
## Instructions
## Create a 2D NumPy array of shape (4, 5) filled with random numbers.




# 🌟 Exercise 5 : Indexing Arrays
## Instructions
## Select the second row from a given 2D NumPy array.




## 🌟 Exercise 6 : Reversing elements
## Instructions
## Reverse the order of elements in a given 1D NumPy array (first element becomes last).




# 🌟 Exercise 7 : Identity Matrix
## Instructions
## Create a 4x4 identity matrix using NumPy.




# 🌟 Exercise 8 : Simple Aggregate Funcs
## Instructions
## Find the sum and average of a given 1D array.




# 🌟 Exercise 9 : Create Array and Change its Structure
## Instructions
## Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.




# 🌟 Exercise 10 : Conditional Selection of Values
## Instructions
## Extract all odd numbers from a given NumPy array.


In [3]:
import numpy as np

In [4]:
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
array_1d[2, ]

np.int64(2)

In [4]:
list = [3.14, 2.17, 0, 1, 2]
converted_list = np.array(list)
converted_list = converted_list.astype(int)
print(converted_list)

[3 2 0 1 2]


In [7]:
array_2d = np.arange(1,10).reshape(3,3)
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
array_2d[1, :]

array([4, 5, 6])

In [12]:
arr_2d = np.random.rand(4,5)
print(arr_2d)

[[0.65357083 0.45163629 0.44149964 0.00228598 0.94245675]
 [0.32027281 0.42453898 0.16775433 0.79121302 0.79054209]
 [0.00984422 0.08302711 0.83206105 0.2720547  0.99708923]
 [0.58816416 0.38322795 0.29349937 0.73930065 0.29881947]]


In [2]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
second_row = array[1, :]
print(f"The second row of the array is: {second_row}")

The second row of the array is: [20 21 22 23 24]


In [12]:
arr_6 = np.arange(1, 10)
print(f"The original array is: {arr_6}")
arr_reversed = arr_6[::-1]
print(f"The reversed array is: {arr_reversed}")

The original array is: [1 2 3 4 5 6 7 8 9]
The reversed array is: [9 8 7 6 5 4 3 2 1]


In [13]:
id_matrix = np.eye(4)
print(id_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
arr_8 = np.arange(1,16)
print(f"The original array is: {arr_8}")
arr_8_sum = arr_8.sum()
print(f"The sum of the array is: {arr_8_sum}")
arr_8_mean = arr_8.mean()
print(f"The mean of the array is: {arr_8_mean}")

The original array is: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
The sum of the array is: 120
The mean of the array is: 8.0


In [19]:
array_9 = np.arange(1,21)
reshaped_array_9 = array_9.reshape(4,5)
print(f"The reshaped array is:\n{reshaped_array_9}")

The reshaped array is:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
array_10 = np.arange(1, 10)
result = array_10[array_10 % 2 != 0]
print(f"The odd numbers in the array are: {result}")

The odd numbers in the array are: [1 3 5 7 9]
